---
# Playbook to install needed packages

- name: Add repos
  apt_repository:
    repo: 'deb http://deb.debian.org/debian buster-backports main contrib'
    state: present
    update_cache: yes

- name: Install packages
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - bzip2
      - curl
      - elinks
      - fish
      - fortune
      - git
      - htop
      - irssi
      - lynx
      - mc
      - mc-data
      - mutt
      - neofetch
      - neomutt
      - oidentd
      - screen
      - tmux
      - vim

- name: Update the repository cache and install ZNC using default release buster-backports
  apt:
    name: znc
    state: latest
    default_release: buster-backports
    update_cache: yes
