---
# task to manage ufw rules

- name: Setup ufw
  ufw:
    state: enabled
    policy: deny

- name: Allow ssh traffic
  ufw:
    rule: allow
    proto: tcp
    port: '{{ item }}'
  with_items:
    - '22'
    - '80'
    - '113'
    - '5000'
